### ISSUE TITLE
Frage: Visualisierungskomponenten auf unterschiedlichenen Rechnern

### ISSUE THREAD

**Issue by hastern** [disco-framework/disco#10]
Ist es möglich eine sekundäre Visualisierungskomponente auf einem zweiten Rechner auszuführen oder müssen alle diese Komponenten auf dem Master-Kontroll-Rechner laufen?

**Comment by exterm** [comment]
Ich glaube nicht, so wie es jetzt gebaut ist. Ließe sich natürlich so erweitern.

Wozu möchtest Du das denn tun? Wir hatten ja damals zwei Beamer am selben Gerät, reicht das nicht?

**Comment by hastern** [comment]
Die Idee war, die relativ aufwendige OpenGL Visualisierung ins Netzwerk zu streamen. 
Ich bin mir nicht sicher ob da ein einzelner Laptop in der Lage zu ist.
