### ISSUE TITLE
Re-enable coverage reporting

### ISSUE THREAD

**Issue by exterm** [disco-framework/disco#14]
We had to disable coverage reporting when upgrading to OTP version 18.

I thought it could be fixed by [upgrading to rebar3](https://github.com/disco-framework/disco/issues/11), but apparently rebar3 has the same problem.

@NobbZ filed an [issue about this](https://github.com/rebar/rebar3/issues/1040) where he was referred to an [issue in OTP itself](https://github.com/erlang/otp/pull/885).

So apparently and hopefully we can just re-enable coverage when we change our OTP 18 build to 18.3 once that's final.

**Comment by NobbZ** [comment]
Leaving this open as a reminder is a good idea. I hope it will be fixed in
18.3.

Philip Müller <notifications@github.com> schrieb am Do., 28. Jan. 2016 um
11:51 Uhr:

**Comment by linearregression** [comment]
I use coverspec with rebar3 to get code coverage but it does not exclude the test directory, which skew the coverage percentage!  

https://github.com/rebar/rebar3/issues/1057

**Comment by NobbZ** [comment]
I'm installing OTP 18.3 right now, since the upstream issue is marked as fixed. I will give it a try if it really works now.

**Comment by NobbZ** [comment]
It does not work :( I still get the same error as with 18.0, 18.1, and 18.2.

**Comment by exterm** [comment]
coverage works just fine on current master.
